previews:
  generation: automatic
services:
  - type: web
    runtime: node
    name: renderPreview
    repo: https://github.com/Saty248/render-preview
    buildCommand: "yarn; yarn build"
    preDeployCommand: "yarn build"
    startCommand: "yarn start"
    plan: free
    branch: main
    envVars:
      - key: TEST_ENV
        value: test_env_value
      - fromGroup: renderPreview env test
